export const ALL_FIELDS = '[PIVOT] ALL_FIELDS';
export const ROWS_TO_PIVOT = '[PIVOT] ROWS_TO_PIVOT';
export const COLUMNS_TO_PIVOT = '[PIVOT] COLUMNS_TO_PIVOT';
export const AGGREGATION_DIMENSION = '[PIVOT] AGGREGATION_DIMENSION';
export const AGGREGATOR = '[PIVOT] AGGREGATOR';
